### ISSUE TITLE
Improve the testing

### ISSUE THREAD

**Issue by nawri14** [CS2103AUG2016-T15-C1/main#11]
fix error and get rid of warnings

**Comment by bartekwozniak93** [comment]
Check LogicManagerTest class.

**Comment by bartekwozniak93** [comment]
Check FindCommandTest class.
TODO

**Comment by bartekwozniak93** [comment]
XmlTaskManagerStorageTest 
TODO

**Comment by bartekwozniak93** [comment]
StorageManagerTest
TODO

**Comment by bartekwozniak93** [comment]
AddCommandTest 
TODO

**Comment by ychoi1997** [comment]
EditCommandTest has been added
